"use client";
import { useEffect,useMemo,useState } from "react";
type Session={session_key:number;year:number;location:string;country_name:string;circuit_short_name:string;date_start:string};
type Driver={driver_number:number;name_acronym?:string;full_name?:string;team_name?:string};
type Point={t:number;speed:number;throttle:number;brake:number;rpm:number;gear:number;drs:number};
type Trace={driver_number:number;lap_number:number;lap_duration:number;trace:Point[];error?:string};
function Line({rows,keyName,max}:{rows:Trace[];keyName:keyof Point;max?:number}){const all=rows.flatMap(r=>r.trace.map(p=>Number(p[keyName]))).filter(Number.isFinite);if(!all.length)return <div className="empty-state">No samples.</div>;const hi=max||Math.max(...all),lo=Math.min(0,...all);const duration=Math.max(...rows.flatMap(r=>r.trace.map(p=>p.t)),1);return <svg className="telemetry-chart" viewBox="0 0 1000 180" preserveAspectRatio="none">{[.25,.5,.75].map(y=><line key={y} x1="0" x2="1000" y1={180*y} y2={180*y} className="chart-grid"/>)}{rows.map((r,idx)=><polyline key={r.driver_number} className={`trace trace-${idx}`} fill="none" vectorEffect="non-scaling-stroke" points={r.trace.map(p=>`${(p.t/duration)*1000},${170-((Number(p[keyName])-lo)/Math.max(hi-lo,1))*155}`).join(" ")}/>)}</svg>}
export default function HistoricalTelemetry(){const [year,setYear]=useState(2026),[sessions,setSessions]=useState<Session[]>([]),[session,setSession]=useState(0),[drivers,setDrivers]=useState<Driver[]>([]),[driver,setDriver]=useState(0),[compare,setCompare]=useState(0),[lap,setLap]=useState(0),[rows,setRows]=useState<Trace[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
useEffect(()=>{fetch(`/api/historical?year=${year}`,{cache:"no-store"}).then(r=>r.json()).then(x=>{setSessions(x.sessions||[]);setSession(x.sessions?.[0]?.session_key||0)})},[year]);
useEffect(()=>{if(!session)return;fetch(`/api/historical?session_key=${session}`,{cache:"no-store"}).then(r=>r.json()).then(x=>{setDrivers(x.drivers||[]);setDriver(x.drivers?.[0]?.driver_number||0);setCompare(x.drivers?.[1]?.driver_number||0);setRows([])})},[session]);
const load=async()=>{if(!session||!driver)return;setLoading(true);setError(null);try{const q=new URLSearchParams({session_key:String(session),driver_number:String(driver)});if(compare)q.set("compare_driver",String(compare));if(lap)q.set("lap_number",String(lap));const r=await fetch(`/api/historical?${q}`,{cache:"no-store"}),x=await r.json();if(!r.ok)throw new Error(x.detail||"Replay failed");setRows(x.telemetry||[])}catch(e){setError(e instanceof Error?e.message:"Replay failed")}finally{setLoading(false)}};
const label=(n:number)=>drivers.find(d=>d.driver_number===n)?.name_acronym||`#${n}`;const active=useMemo(()=>sessions.find(s=>s.session_key===session),[sessions,session]);
return <section className="historical-lab"><div className="panel-head"><div><span className="kicker">REAL OPENF1 / HISTORICAL</span><h2>Telemetry Workstation</h2></div><span className="panel-note">observed broadcast samples · no synthetic trace</span></div><div className="replay-controls"><select value={year} onChange={e=>setYear(Number(e.target.value))}>{[2026,2025,2024,2023].map(y=><option key={y}>{y}</option>)}</select><select value={session} onChange={e=>setSession(Number(e.target.value))}>{sessions.map(s=><option key={s.session_key} value={s.session_key}>{s.location} · {new Date(s.date_start).toLocaleDateString()}</option>)}</select><select value={driver} onChange={e=>setDriver(Number(e.target.value))}>{drivers.map(d=><option key={d.driver_number} value={d.driver_number}>{d.name_acronym||d.full_name}</option>)}</select><select value={compare} onChange={e=>setCompare(Number(e.target.value))}><option value={0}>No comparison</option>{drivers.filter(d=>d.driver_number!==driver).map(d=><option key={d.driver_number} value={d.driver_number}>{d.name_acronym||d.full_name}</option>)}</select><input type="number" min="0" placeholder="Lap (0 = fastest)" value={lap||""} onChange={e=>setLap(Number(e.target.value)||0)}/><button className="primary-button" onClick={()=>void load()} disabled={loading}>{loading?"Loading real data…":"Load telemetry"}</button></div>{error&&<div className="inline-error">{error}</div>}{rows.length>0&&<><div className="trace-legend">{rows.map((r,i)=><span key={r.driver_number} className={`legend-${i}`}><i/> {label(r.driver_number)} · L{r.lap_number} · {Number(r.lap_duration).toFixed(3)}s</span>)}</div>{([["Speed","speed",360],["Throttle","throttle",100],["Brake","brake",100],["RPM","rpm",15000],["Gear","gear",8],["DRS","drs",14]] as const).map(([name,key,max])=><div className="telemetry-strip" key={key}><div className="strip-label"><strong>{name}</strong><span>{key==="speed"?"km/h":key==="rpm"?"rpm":key==="throttle"||key==="brake"?"%":""}</span></div><Line rows={rows} keyName={key} max={max}/></div>)}<p className="footnote">{active?.location}: traces are direct OpenF1 car_data samples for the selected completed race lap. Brake is broadcast channel data, not brake pressure.</p></>}</section>}
