"""Regime-aware next-lap intelligence with disjoint conformal calibration.

A single lap-time regressor is a poor model for Formula 1 because pit and neutralized
laps are generated by different mechanisms. This module first models the target-lap
regime, then predicts pace only for green laps. Predictive intervals are calibrated
on a whole race that is disjoint from both model selection and the sealed test race.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, log_loss
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from .lap_intelligence import (
    CATEGORICAL_FEATURES,
    FEATURES,
    NUMERIC_FEATURES,
    LapModelSpec,
    build_lap_estimator,
    live_feature_rows,
)
from .value_parsing import strict_optional_bool

REGIMES = ("green", "neutralized", "pit")


@dataclass(frozen=True)
class MixtureBenchmark:
    test_session: int
    selected_regressor: str
    green_rows: int
    green_mae_s: float
    green_rmse_s: float
    interval_coverage: float
    interval_mean_width_s: float
    regime_accuracy: float
    regime_log_loss: float


def attach_regime_labels(dataset: pd.DataFrame, lap_rows: list[dict[str, Any]],
                         pit_rows: list[dict[str, Any]] | None = None) -> pd.DataFrame:
    """Attach target-only labels without adding future information to model features."""
    output = dataset.copy()
    laps = pd.DataFrame(lap_rows)
    if laps.empty:
        raise ValueError("Lap rows are required for regime labels")
    required = {"session_key", "driver_number", "lap_number", "is_pit_out_lap"}
    if required - set(laps):
        raise ValueError("Lap rows lack regime identity/pit-out columns")
    identity = laps[["session_key", "driver_number", "lap_number"]].copy()
    identity["is_pit_out_lap"] = [
        strict_optional_bool(value, field="openf1.laps.is_pit_out_lap")
        for value in laps["is_pit_out_lap"]
    ]
    for column in required:
        identity[column] = pd.to_numeric(identity[column], errors="coerce")

    pit_keys: set[tuple[int, int, int]] = set()
    pits = pd.DataFrame(pit_rows or [])
    if not pits.empty and required <= set(pits):
        for _, row in pits.dropna(subset=list(required)).iterrows():
            pit_keys.add((int(row.session_key), int(row.driver_number), int(row.lap_number)))

    out_map = {
        (int(row.session_key), int(row.driver_number), int(row.lap_number)): row.is_pit_out_lap
        for _, row in identity.dropna(subset=["session_key", "driver_number", "lap_number"]).iterrows()
    }
    labels = []
    for _, row in output.iterrows():
        key = (int(row.session_key), int(row.driver_number), int(row.lap_number))
        pit_out = out_map.get(key)
        if key in pit_keys or pit_out is True:
            labels.append("pit")
        elif pit_out is None:
            labels.append(None)
        elif float(row.get("safety_car_active", 0) or 0) > 0:
            labels.append("neutralized")
        else:
            labels.append("green")
    output["lap_regime"] = pd.Categorical(labels, categories=REGIMES)
    return output


def build_regime_classifier() -> Pipeline:
    numeric = Pipeline([("impute", SimpleImputer(strategy="median", add_indicator=True))])
    categorical = Pipeline([
        ("impute", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ])
    preprocess = ColumnTransformer([
        ("numeric", numeric, NUMERIC_FEATURES),
        ("categorical", categorical, CATEGORICAL_FEATURES),
    ])
    classifier = ExtraTreesClassifier(
        n_estimators=500,
        min_samples_leaf=3,
        max_features=0.8,
        class_weight="balanced_subsample",
        random_state=42,
        n_jobs=-1,
    )
    return Pipeline([("preprocess", preprocess), ("model", classifier)])


def _pace_metrics(actual: np.ndarray, predicted: np.ndarray) -> tuple[float, float]:
    error = np.asarray(predicted, dtype=float) - np.asarray(actual, dtype=float)
    if not len(error) or not np.isfinite(error).all():
        raise ValueError("Invalid green-lap pace predictions")
    return float(np.mean(np.abs(error))), float(np.sqrt(np.mean(error ** 2)))


def _conformal_radius(actual: np.ndarray, predicted: np.ndarray, alpha: float) -> float:
    residual = np.abs(np.asarray(actual, dtype=float) - np.asarray(predicted, dtype=float))
    residual = residual[np.isfinite(residual)]
    if len(residual) < 20:
        raise ValueError("Need at least 20 calibration green laps for conformal interval")
    rank = min(1.0, np.ceil((len(residual) + 1) * (1 - alpha)) / len(residual))
    return float(np.quantile(residual, rank, method="higher"))


def _fit_regressor(train: pd.DataFrame, spec: LapModelSpec):
    green = train[train.target_valid & train.lap_regime.eq("green")]
    if len(green) < 50:
        raise ValueError("Insufficient green laps for pace regression")
    model = build_lap_estimator(spec)
    model.fit(green[FEATURES], green.target_s)
    return model


def _select_regressor(train: pd.DataFrame, validation: pd.DataFrame,
                      specs: tuple[LapModelSpec, ...]) -> tuple[LapModelSpec, list[dict[str, Any]]]:
    target = validation[validation.target_valid & validation.lap_regime.eq("green")]
    if target.empty:
        raise ValueError("Validation race has no green laps")
    trials = []
    for spec in specs:
        try:
            model = _fit_regressor(train, spec)
            pred = model.predict(target[FEATURES])
            mae, rmse = _pace_metrics(target.target_s.to_numpy(), pred)
            trials.append({"model": spec.name, "params": dict(spec.params), "mae_s": mae, "rmse_s": rmse})
        except (ValueError, RuntimeError, MemoryError) as exc:
            trials.append({"model": spec.name, "params": dict(spec.params), "mae_s": np.inf,
                           "rmse_s": np.inf, "error": str(exc)})
    valid = [row for row in trials if np.isfinite(row["mae_s"])]
    if not valid:
        raise ValueError("No green-lap regressor completed validation")
    winner = min(valid, key=lambda row: (row["mae_s"], row["model"]))
    return next(spec for spec in specs if spec.name == winner["model"]), trials


def _full_regime_probability(classifier: Pipeline, frame: pd.DataFrame) -> np.ndarray:
    observed = classifier.predict_proba(frame[FEATURES])
    classes = list(classifier.classes_)
    full = np.full((len(frame), len(REGIMES)), 1e-12, dtype=float)
    for source_index, name in enumerate(classes):
        if name in REGIMES:
            full[:, REGIMES.index(name)] = observed[:, source_index]
    full /= full.sum(axis=1, keepdims=True)
    return full


def fit_mixture(datasets: list[pd.DataFrame], *,
                specs: tuple[LapModelSpec, ...] | None = None,
                alpha: float = 0.10) -> tuple[dict[str, Any], pd.DataFrame, dict[str, Any]]:
    """Fit/tune/calibrate/test on four disjoint chronological race blocks."""
    if not 0 < alpha < 0.5:
        raise ValueError("alpha must be between 0 and 0.5")
    if len(datasets) < 4:
        raise ValueError("Need train, tuning, calibration and sealed test races")
    if any("lap_regime" not in frame for frame in datasets):
        raise ValueError("Datasets must contain lap_regime labels")
    specs = specs or (
        LapModelSpec("hist_gradient_boosting", {}),
        LapModelSpec("extra_trees", {}),
    )
    train = pd.concat(datasets[:-3], ignore_index=True)
    tuning = datasets[-3].copy()
    calibration = datasets[-2].copy()
    test = datasets[-1].copy()

    selected, trials = _select_regressor(train, tuning, specs)
    pre_cal = pd.concat([train, tuning], ignore_index=True)
    regressor = _fit_regressor(pre_cal, selected)
    classifier_train = pre_cal[pre_cal.lap_regime.notna()].copy()
    if classifier_train.empty:
        raise ValueError("No known lap-regime labels are available for classifier training")
    classifier = build_regime_classifier().fit(
        classifier_train[FEATURES], classifier_train.lap_regime.astype(str)
    )

    cal_green = calibration[calibration.target_valid & calibration.lap_regime.eq("green")]
    if cal_green.empty:
        raise ValueError("Calibration race has no green laps")
    cal_prediction = regressor.predict(cal_green[FEATURES])
    radius = _conformal_radius(cal_green.target_s.to_numpy(), cal_prediction, alpha)

    test_green = test[test.target_valid & test.lap_regime.eq("green")]
    if test_green.empty:
        raise ValueError("Sealed test race has no green laps")
    green_prediction = regressor.predict(test_green[FEATURES])
    green_mae, green_rmse = _pace_metrics(test_green.target_s.to_numpy(), green_prediction)
    lower, upper = green_prediction - radius, green_prediction + radius
    coverage = float(((test_green.target_s.to_numpy() >= lower)
                      & (test_green.target_s.to_numpy() <= upper)).mean())

    regime_test = test[test.lap_regime.notna()].copy()
    if regime_test.empty:
        raise ValueError("Sealed test has no known lap-regime labels")
    regime_probability = _full_regime_probability(classifier, regime_test)
    regime_prediction = np.asarray(REGIMES, dtype=object)[np.argmax(regime_probability, axis=1)]
    truth = regime_test.lap_regime.astype(str).to_numpy()
    regime_accuracy = float(accuracy_score(truth, regime_prediction))
    regime_loss = float(log_loss(truth, regime_probability, labels=list(REGIMES)))

    summary = MixtureBenchmark(
        test_session=int(test.session_key.iloc[0]),
        selected_regressor=selected.name,
        green_rows=len(test_green),
        green_mae_s=green_mae,
        green_rmse_s=green_rmse,
        interval_coverage=coverage,
        interval_mean_width_s=2 * radius,
        regime_accuracy=regime_accuracy,
        regime_log_loss=regime_loss,
    )
    artifact = {
        "schema_version": 2,
        "task": "next_lap_mixture",
        "features": FEATURES,
        "regimes": list(REGIMES),
        "regime_classifier": classifier,
        "pace_regressor": regressor,
        "selected_regressor": selected.name,
        "conformal_alpha": alpha,
        "conformal_radius_s": radius,
        "trained_through_session": int(tuning.session_key.iloc[0]),
        "calibration_session": int(calibration.session_key.iloc[0]),
        "sealed_test_session": int(test.session_key.iloc[0]),
    }
    audit = {
        "protocol": "older races fit -> one race tune -> one race conformal calibration -> sealed test",
        "regressor_trials": [{key: (None if value == np.inf else value) for key, value in row.items()}
                             for row in trials],
        "conformal_radius_s": radius,
        "alpha": alpha,
        "test_updates_model": False,
        "regime_definition": {
            "pit": "pit endpoint lap_number or laps.is_pit_out_lap",
            "neutralized": "Safety Car/VSC state already active at target-lap start",
            "green": "all other target laps",
        },
        "limitation": "Unexpected neutralization beginning mid-lap is not inferable from already-known state.",
    }
    return artifact, pd.DataFrame([asdict(summary)]), audit


def predict_live_mixture(artifact: dict[str, Any], snapshot: dict[str, Any]) -> pd.DataFrame:
    if artifact.get("task") != "next_lap_mixture" or artifact.get("features") != FEATURES:
        raise ValueError("Mixture artifact schema mismatch")
    frame = live_feature_rows(snapshot)
    if frame.empty:
        return frame
    classifier = artifact["regime_classifier"]
    probabilities = _full_regime_probability(classifier, frame)
    clean_pace = artifact["pace_regressor"].predict(frame[FEATURES])
    radius = float(artifact["conformal_radius_s"])
    output = frame.copy()
    output["predicted_green_lap_s"] = clean_pace
    output["green_lap_lower_s"] = clean_pace - radius
    output["green_lap_upper_s"] = clean_pace + radius
    for index, name in enumerate(REGIMES):
        output[f"p_{name}"] = probabilities[:, index]
    return output
